// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdWfHTEBPhwPGjAse2LTDNbrLVrRRR9s0',
    appId: '1:916296928419:web:a4ab0d11a372ad74638316',
    messagingSenderId: '916296928419',
    projectId: 'e-business-ui-1',
    authDomain: 'e-business-ui-1.firebaseapp.com',
    storageBucket: 'e-business-ui-1.appspot.com',
    measurementId: 'G-CYMRDC50P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0bEC0wm1NtKzlIEoyHTOJPJmLynr28j0',
    appId: '1:916296928419:android:1c75b8458a51bfc1638316',
    messagingSenderId: '916296928419',
    projectId: 'e-business-ui-1',
    storageBucket: 'e-business-ui-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF_x8eg3PsP0hO256WQd15N20y_e0Zk8s',
    appId: '1:916296928419:ios:9aa6039bf118bbc2638316',
    messagingSenderId: '916296928419',
    projectId: 'e-business-ui-1',
    storageBucket: 'e-business-ui-1.appspot.com',
    androidClientId: '916296928419-4b8lhq9c31rnbcgnndg46osu5kjve4k4.apps.googleusercontent.com',
    iosClientId: '916296928419-r3fi2ii1jh9t1it5m7aquhhd6gbfrr2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF_x8eg3PsP0hO256WQd15N20y_e0Zk8s',
    appId: '1:916296928419:ios:9aa6039bf118bbc2638316',
    messagingSenderId: '916296928419',
    projectId: 'e-business-ui-1',
    storageBucket: 'e-business-ui-1.appspot.com',
    androidClientId: '916296928419-4b8lhq9c31rnbcgnndg46osu5kjve4k4.apps.googleusercontent.com',
    iosClientId: '916296928419-r3fi2ii1jh9t1it5m7aquhhd6gbfrr2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
